# ColFormat { #reactable.ColFormat }

`ColFormat(prefix=None, suffix=None, digits=None, separators=None, percent=None, currency=None, datetime=None, date=None, time=None, hour12=None, locales=None)`

Specify formatting for a Column.

## Parameters

| Name         | Type                   | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Default   |
|--------------|------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| `prefix`     | str \| None            | Prefix string.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |
| `suffix`     | str \| None            | Suffix string.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |
| `digits`     | int \| None            | Number of decimal digits to use for numbers.                                                                                                                                                                                                                                                                                                                                                                                                                                                       | `None`    |
| `separators` | bool \| None           | Whether to use grouping separators for numbers, such as thousands separators or thousand/lakh/crore separators. The format is locale-dependent.                                                                                                                                                                                                                                                                                                                                                    | `None`    |
| `percent`    | bool \| None           | Format number as a percentage? The format is locale-dependent.                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |
| `currency`   | StrIsoCurrency \| None | Currency format. An ISO 4217 currency code such as "USD" for the US dollar, "EUR" for the euro, or "CNY" for the Chinese RMB. The format is locale-dependent.                                                                                                                                                                                                                                                                                                                                      | `None`    |
| `datetime`   | bool \| None           | Whether to format as a locale-dependent date-time.                                                                                                                                                                                                                                                                                                                                                                                                                                                 | `None`    |
| `date`       | bool \| None           | Whether to format as a locale-dependent date.                                                                                                                                                                                                                                                                                                                                                                                                                                                      | `None`    |
| `time`       | bool \| None           | Whether to format as a locale-dependent time.                                                                                                                                                                                                                                                                                                                                                                                                                                                      | `None`    |
| `hour12`     | bool \| None           | Whether to use 12-hour time (True) or 24-hour time (False). The default time convention is locale-dependent.                                                                                                                                                                                                                                                                                                                                                                                       | `None`    |
| `locales`    | bool \| None           | Locales to use for number, date, time, and currency formatting. A character vector of BCP 47 language tags, such as "en-US" for English (United States), "hi" for Hindi, or "sv-SE" for Swedish (Sweden). Defaults to the locale of the user's browser.  Multiple locales may be specified to provide a fallback language in case a locale is unsupported. When multiple locales are specified, the first supported locale will be used.  See a list of common BCP 47 language tags for reference. | `None`    |