# Language { #reactable.Language }

`Language(sort_label='Sort {name}', filter_placeholder='', filter_label='Filter {name}', search_placeholder='Search', search_label='Search', no_data='No rows found', page_next='Next', page_previous='Previous', page_numbers='{page} of {pages}', page_info='{rowStart}–{rowEnd} of {rows} rows', page_size_options='Show {rows}', page_next_label='Next page', page_previous_label='Previous page', page_number_label='Page {page}', page_jump_label='Go to page', page_size_options_label='Rows per page', group_expand_label='Toggle group', details_expand_label='Toggle details', select_all_rows_label='Select all rows', select_all_sub_rows_label='Select all rows in group', select_row_label='Select row')`

Language options.

## Parameters

| Name                        | Type   | Description                                                                                                                                                                                  | Default                                |
|-----------------------------|--------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------|
| `sort_label`                | str    | Accessible label for column sort buttons. Takes a `{name}` parameter for the column name.                                                                                                    | `'Sort {name}'`                        |
| `filter_placeholder`        | str    | Placeholder for column filter inputs.                                                                                                                                                        | `''`                                   |
| `filter_label`              | str    | Accessible label for column filter inputs. Takes a `{name}` parameter for the column name.                                                                                                   | `'Filter {name}'`                      |
| `search_placeholder`        | str    | Placeholder for the table search input.                                                                                                                                                      | `'Search'`                             |
| `search_label`              | str    | Accessible label for the table search input.                                                                                                                                                 | `'Search'`                             |
| `no_data`                   | str    | Placeholder text when the table has no data.                                                                                                                                                 | `'No rows found'`                      |
| `page_next`                 | str    | Text for the next page button.                                                                                                                                                               | `'Next'`                               |
| `page_previous`             | str    | Text for the previous page button.                                                                                                                                                           | `'Previous'`                           |
| `page_numbers`              | str    | Text for the page numbers info. Only used with the "jump" and "simple" pagination types. Takes the following parameters: {page} for the current page, {pages} for the total number of pages. | `'{page} of {pages}'`                  |
| `page_info`                 | str    | Text for the page info. Takes the following parameters: `{rowStart}` for the starting row of the page, `{rowEnd}` for the ending row of the page, `{rows}` for the total number of rows.     | `'{rowStart}–{rowEnd} of {rows} rows'` |
| `page_size_options`         | str    | Text for the page size options input. Takes a {rows} parameter for the page size options input.                                                                                              | `'Show {rows}'`                        |
| `page_next_label`           | str    | Accessible label for the next page button.                                                                                                                                                   | `'Next page'`                          |
| `page_previous_label`       | str    | Accessible label for the previous page button.                                                                                                                                               | `'Previous page'`                      |
| `page_number_label`         | str    | Accessible label for the page number buttons. Only used with the the "numbers" pagination type. Takes a {page} parameter for the page number.                                                | `'Page {page}'`                        |
| `page_jump_label`           | str    | Accessible label for the page jump input. Only used with the "jump" pagination type.                                                                                                         | `'Go to page'`                         |
| `page_size_options_label`   | str    | Accessible label for the page size options input.                                                                                                                                            | `'Rows per page'`                      |
| `group_expand_label`        | str    | Accessible label for the row group expand button.                                                                                                                                            | `'Toggle group'`                       |
| `details_expand_label`      | str    | Accessible label for the row details expand button.                                                                                                                                          | `'Toggle details'`                     |
| `select_all_rows_label`     | str    | Accessible label for the select all rows checkbox.                                                                                                                                           | `'Select all rows'`                    |
| `select_all_sub_rows_label` | str    | Accessible label for the select all sub rows checkbox.                                                                                                                                       | `'Select all rows in group'`           |
| `select_row_label`          | str    | Accessible label for the select row checkbox.                                                                                                                                                | `'Select row'`                         |